### PR TITLE
Changes to makefile

### PR DESCRIPTION
**Pull request by samueloph**
This will fix the regression introduced on https://github.com/wiire/pixiewps/pull/32, plus some other changes that can be seen on the commit messages.

Changes tested and ok.

### CODE REVIEW

**Comment by samueloph** [comment]
Well, i accidentally pushed a manpage on the master branch, @wiire i can remove that if you want, but i think you'd like that.

**Comment by wiire** [comment]
That's great! Thank you and everyone else who was involved in the changes. I really appreciate your time and effort.

**Comment by mahmoodalam62** [comment]
Need fucking help. Last hope pixiewps but also failed.
kali8

**Comment by soxrok2212** [comment]
There is no issue. The lin was not found. That's it.

**Pull request merged**
